import type { MetadataRoute } from "next";

// PWA manifest — Next auto-links this at /manifest.webmanifest.
// Icons are generated by scripts/gen-brand-icons.mjs into public/brand/.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Dewlock — Sui DeFi Copilot",
    short_name: "Dewlock",
    description: "Every transaction, sealed before you sign.",
    start_url: "/",
    display: "standalone",
    background_color: "#0c131d",
    theme_color: "#0c89e9",
    icons: [
      {
        src: "/brand/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/brand/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
